// Copyright 2026 Philterd, LLC.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package suggest

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/philterd/philterscope/internal/ollama"
	"github.com/philterd/philterscope/pkg/model"
)

// LLMSuggester implements Suggester using an LLM.
type LLMSuggester struct {
	Client *ollama.Client
}

// NewLLMSuggester creates a new LLMSuggester.
func NewLLMSuggester(client *ollama.Client) *LLMSuggester {
	return &LLMSuggester{Client: client}
}

// Suggest returns recommendations generated by the LLM.
func (s *LLMSuggester) Suggest(result model.AuditResult) []model.Recommendation {
	ctx := context.Background()

	prompt := s.buildPrompt(result)
	response, err := s.Client.Generate(ctx, prompt)
	if err != nil {
		return []model.Recommendation{{
			Entity:      "AI_ERROR",
			Description: fmt.Sprintf("Failed to generate AI recommendations: %v", err),
			Action:      "Check Ollama status and configuration.",
			IsAI:        true,
		}}
	}

	return s.parseResponse(response)
}

func (s *LLMSuggester) buildPrompt(result model.AuditResult) string {
	var sb strings.Builder
	sb.WriteString("You are a PII redaction policy expert. Based on the following audit result, suggest policy changes in Philter. ")
	sb.WriteString("Provide the suggestions in JSON format as an array of objects with fields: entity, description, action, snippet.\n\n")
	sb.WriteString(fmt.Sprintf("Audit Result: F1 Score: %.2f, Precision: %.2f, Recall: %.2f\n", result.F1Score, result.Precision, result.Recall))
	sb.WriteString("Entity Metrics:\n")
	for entity, recall := range result.EntityMetrics {
		sb.WriteString(fmt.Sprintf("- %s: Recall %.1f%%\n", entity, recall*100))
	}
	sb.WriteString("\nJSON Output Only:")
	return sb.String()
}

func (s *LLMSuggester) parseResponse(response string) []model.Recommendation {
	// Simple JSON extraction from the response
	start := strings.Index(response, "[")
	end := strings.LastIndex(response, "]")
	if start == -1 || end == -1 || start > end {
		return []model.Recommendation{{
			Entity:      "AI_PARSE_ERROR",
			Description: "Could not parse AI recommendations from response.",
			Action:      "Review AI output manually.",
			Snippet:     response,
			IsAI:        true,
		}}
	}

	var recs []model.Recommendation
	if err := json.Unmarshal([]byte(response[start:end+1]), &recs); err != nil {
		return []model.Recommendation{{
			Entity:      "AI_PARSE_ERROR",
			Description: fmt.Sprintf("Failed to decode AI recommendations: %v", err),
			Action:      "Review AI output manually.",
			Snippet:     response,
			IsAI:        true,
		}}
	}

	for i := range recs {
		recs[i].IsAI = true
	}
	return recs
}
