// Copyright 2026 Philterd, LLC.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package model

import "time"

// Redactor defines the interface for redaction services.
type Redactor interface {
	Redact(text string) (string, []Span, error)
}

// AuditResult holds the outcome of an auditing run.
type AuditResult struct {
	ID               interface{}               `json:"id" bson:"_id,omitempty"`
	Timestamp        time.Time                 `json:"timestamp" bson:"timestamp"`
	TotalDocuments   int                       `json:"total_documents" bson:"total_documents"`
	Precision        float64                   `json:"precision" bson:"precision"`
	Recall           float64                   `json:"recall" bson:"recall"`
	F1Score          float64                   `json:"f1_score" bson:"f1_score"`
	Details          []Result                  `json:"details" bson:"details"`
	Policy           map[string]interface{}    `json:"policy" bson:"policy"`                       // Philter JSON configuration
	Recommendations  []Recommendation          `json:"recommendations" bson:"recommendations"`     // Suggested policy changes
	EntityMetrics    map[string]float64        `json:"entity_metrics" bson:"entity_metrics"`       // Recall per entity type
	ConfusionMatrix  map[string]map[string]int `json:"confusion_matrix" bson:"confusion_matrix"`   // Expected label -> actual label -> count
	Threshold        float64                   `json:"threshold" bson:"threshold"`                 // Global threshold used for suggestions
	EntityThresholds map[string]float64        `json:"entity_thresholds" bson:"entity_thresholds"` // Per-entity thresholds
	GroupName        string                    `json:"group_name" bson:"group_name"`               // Assigned group name
	Notes            string                    `json:"notes" bson:"notes"`                         // User-provided notes
	FilesSkipped     int                       `json:"files_skipped" bson:"files_skipped"`         // Input files that could not be scored
	Skipped          []SkippedFile             `json:"skipped,omitempty" bson:"skipped,omitempty"` // Why each was skipped
}

// SkippedFile records an input file that could not be scored. A skipped file is
// not the same as one that scored zero: it contributed nothing to the metrics.
type SkippedFile struct {
	Filename string `json:"filename" bson:"filename"`
	Reason   string `json:"reason" bson:"reason"`
}

// HistoryEntry represents a past audit result.
type HistoryEntry struct {
	ID        interface{}            `json:"id" bson:"_id,omitempty"`
	Timestamp time.Time              `json:"timestamp" bson:"timestamp"`
	Precision float64                `json:"precision" bson:"precision"`
	Recall    float64                `json:"recall" bson:"recall"`
	F1Score   float64                `json:"f1_score" bson:"f1_score"`
	Threshold float64                `json:"threshold" bson:"threshold"`
	Policy    map[string]interface{} `json:"policy" bson:"policy"`
	GroupName string                 `json:"group_name" bson:"group_name"`
}

// AuditHistory represents a collection of past audit results.
type AuditHistory struct {
	Entries []HistoryEntry `json:"entries"`
	Error   string         `json:"error,omitempty"` // Connection or authentication error
}

// Recommendation holds a suggested policy change.
type Recommendation struct {
	Entity      string `json:"entity"`
	Description string `json:"description"`
	Action      string `json:"action"`
	Snippet     string `json:"snippet"`
	Resolved    bool   `json:"resolved" bson:"resolved"`   // Mark as resolved in the database
	Dismissed   bool   `json:"dismissed" bson:"dismissed"` // Mark as dismissed in the database
	IsAI        bool   `json:"is_ai" bson:"is_ai"`         // Whether the recommendation was generated by AI
}

// Result is a single comparison outcome.
type Result struct {
	Filename string    `json:"filename" bson:"filename"`
	Expected string    `json:"expected" bson:"expected"`
	Actual   string    `json:"actual" bson:"actual"`
	Spans    []Span    `json:"spans" bson:"spans"` // Detected or labeled spans
	TP       int       `json:"tp" bson:"tp"`       // True Positives
	FP       int       `json:"fp" bson:"fp"`       // False Positives
	FN       int       `json:"fn" bson:"fn"`       // False Negatives
	Overlaps []Overlap `json:"overlaps" bson:"overlaps"`
}

// Span represents a labeled PII fragment.
type Span struct {
	Id             string  `json:"id" bson:"id"`
	CharacterStart int     `json:"characterStart" bson:"characterstart"`
	CharacterEnd   int     `json:"characterEnd" bson:"characterend"`
	FilterType     string  `json:"filterType" bson:"filterType"`
	Context        string  `json:"context" bson:"context"`
	DocumentId     string  `json:"documentId" bson:"documentId"`
	Confidence     float64 `json:"confidence" bson:"confidence"`
	Text           string  `json:"text" bson:"text"`
	Replacement    string  `json:"replacement" bson:"replacement"`
	Salt           string  `json:"salt" bson:"salt"`
	Ignored        bool    `json:"ignored" bson:"ignored"`

	// Compatibility aliases for the audit engine and UI
	Label string `json:"label" bson:"label"`
}

// Overlap type
const (
	OverlapExact   = "EXACT"
	OverlapPartial = "PARTIAL"
	OverlapNone    = "NONE"
)

// Overlap describes the relationship between a Philter span and a Golden span.
type Overlap struct {
	Golden Span   `json:"golden" bson:"golden"`
	Actual Span   `json:"actual" bson:"actual"`
	Type   string `json:"type" bson:"type"` // EXACT, PARTIAL, NONE
}
