// Copyright 2026 Philterd, LLC.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package model

import "time"

// Redactor defines the interface for redaction services.
type Redactor interface {
	Redact(text string) (string, []Span, error)
}

// AuditResult holds the outcome of an auditing run.
type AuditResult struct {
	ID               interface{}               `json:"id" bson:"_id,omitempty"`
	Timestamp        time.Time                 `json:"timestamp" bson:"timestamp"`
	TotalDocuments   int                       `json:"total_documents" bson:"total_documents"`
	Precision        float64                   `json:"precision" bson:"precision"`
	Recall           float64                   `json:"recall" bson:"recall"`
	F1Score          float64                   `json:"f1_score" bson:"f1_score"`
	Details          []Result                  `json:"details" bson:"details"`
	Policy           map[string]interface{}    `json:"policy" bson:"policy"`                       // Philter JSON configuration
	Recommendations  []Recommendation          `json:"recommendations" bson:"recommendations"`     // Suggested policy changes
	EntityMetrics    map[string]float64        `json:"entity_metrics" bson:"entity_metrics"`       // Recall per entity type
	EntityStats      map[string]EntityStat     `json:"entity_stats" bson:"entity_stats"`           // Counts and both rates per entity type
	ConfusionMatrix  map[string]map[string]int `json:"confusion_matrix" bson:"confusion_matrix"`   // Expected label -> actual label -> count
	Threshold        float64                   `json:"threshold" bson:"threshold"`                 // Global recall threshold used for suggestions
	PrecisionFloor   float64                   `json:"precision_floor" bson:"precision_floor"`     // Precision below which an entity is flagged as likely misconfigured
	EntityThresholds map[string]float64        `json:"entity_thresholds" bson:"entity_thresholds"` // Per-entity thresholds
	GroupName        string                    `json:"group_name" bson:"group_name"`               // Assigned group name
	Notes            string                    `json:"notes" bson:"notes"`                         // User-provided notes
	FilesSkipped     int                       `json:"files_skipped" bson:"files_skipped"`         // Input files that could not be scored
	Skipped          []SkippedFile             `json:"skipped,omitempty" bson:"skipped,omitempty"` // Why each was skipped
}

// SkippedFile records an input file that could not be scored. A skipped file is
// not the same as one that scored zero: it contributed nothing to the metrics.
type SkippedFile struct {
	Filename string `json:"filename" bson:"filename"`
	Reason   string `json:"reason" bson:"reason"`
}

// HistoryEntry represents a past audit result.
type HistoryEntry struct {
	ID        interface{}            `json:"id" bson:"_id,omitempty"`
	Timestamp time.Time              `json:"timestamp" bson:"timestamp"`
	Precision float64                `json:"precision" bson:"precision"`
	Recall    float64                `json:"recall" bson:"recall"`
	F1Score   float64                `json:"f1_score" bson:"f1_score"`
	Threshold float64                `json:"threshold" bson:"threshold"`
	Policy    map[string]interface{} `json:"policy" bson:"policy"`
	GroupName string                 `json:"group_name" bson:"group_name"`
}

// AuditHistory represents a collection of past audit results.
type AuditHistory struct {
	Entries []HistoryEntry `json:"entries"`
	Error   string         `json:"error,omitempty"` // Connection or authentication error
}

// Recommendation kinds. The kind says what measurement produced the
// recommendation, so a consumer can tell an action to take from a warning to
// investigate without parsing the description.
const (
	// KindRecallGap is an entity whose recall is below its threshold. This is
	// the kind that asks for a policy change.
	KindRecallGap = "recall_below_threshold"
	// KindPrecisionCollapsed is an entity redacting so far beyond its golden
	// spans that the filter is more likely misconfigured than deliberately
	// wide. It is a warning, not an instruction to redact less.
	KindPrecisionCollapsed = "precision_collapsed"
	// KindAI is a recommendation generated by an LLM rather than by a
	// measurement, so it carries no structured evidence.
	KindAI = "ai"
)

// Policy change types carried on a Recommendation.
const (
	ChangeEnableFilter    = "enable_filter"
	ChangeReviewFilter    = "review_filter"
	ChangeLowerConfidence = "lower_confidence_threshold"
	ChangeRaiseConfidence = "raise_confidence_threshold"
	ChangeNone            = "none"
)

// PolicyChange is the proposed edit in structured form, so an importer such as
// the Redaction Policy Editor does not have to parse the snippet or the prose.
// Filter names the identifier key in the Philter policy, which is not always
// the entity label: an entity the policy has no filter for leaves it empty.
type PolicyChange struct {
	Type   string   `json:"type" bson:"type"`
	Filter string   `json:"filter,omitempty" bson:"filter,omitempty"`
	Field  string   `json:"field,omitempty" bson:"field,omitempty"`
	From   *float64 `json:"from,omitempty" bson:"from,omitempty"`
	To     *float64 `json:"to,omitempty" bson:"to,omitempty"`
}

// Projection is what the change is expected to do to the entity's metrics.
//
// Predicted separates a number computed from the audit's own detections from
// one that cannot be known without re-running the audit. Enabling a filter that
// did not run produces no detections to measure, so its effect is unpredicted
// and Recall and Precision stay nil. Raising a confidence threshold only drops
// detections already in hand, so its effect is computed exactly. Never present
// an unpredicted projection as though it were measured.
type Projection struct {
	Predicted bool     `json:"predicted" bson:"predicted"`
	Recall    *float64 `json:"recall,omitempty" bson:"recall,omitempty"`
	Precision *float64 `json:"precision,omitempty" bson:"precision,omitempty"`
	Note      string   `json:"note" bson:"note"`
}

// Recommendation holds a suggested policy change.
//
// ID is stable across runs for the same kind and entity, and is what resolve
// and dismiss address. One entity can carry more than one recommendation, so
// the entity alone no longer identifies a recommendation.
type Recommendation struct {
	ID          string `json:"id" bson:"id"`
	Kind        string `json:"kind" bson:"kind"`
	Entity      string `json:"entity"`
	Description string `json:"description"`
	Action      string `json:"action"`
	Snippet     string `json:"snippet"`

	// The measurement that produced this recommendation.
	Metric    string  `json:"metric" bson:"metric"`       // "recall" or "precision"
	Value     float64 `json:"value" bson:"value"`         // The measured value
	Threshold float64 `json:"threshold" bson:"threshold"` // What it was compared against

	// The entity's standing on both metrics at audit time, so a consumer can
	// see the cost side of the trade and not just the gap being closed. Nil
	// where the audit produced no basis for the number.
	CurrentRecall    *float64 `json:"current_recall,omitempty" bson:"current_recall,omitempty"`
	CurrentPrecision *float64 `json:"current_precision,omitempty" bson:"current_precision,omitempty"`

	Change     *PolicyChange `json:"change,omitempty" bson:"change,omitempty"`
	Projection *Projection   `json:"projection,omitempty" bson:"projection,omitempty"`

	Resolved  bool `json:"resolved" bson:"resolved"`   // Mark as resolved in the database
	Dismissed bool `json:"dismissed" bson:"dismissed"` // Mark as dismissed in the database
	IsAI      bool `json:"is_ai" bson:"is_ai"`         // Whether the recommendation was generated by AI
}

// EntityStat holds the counts behind one entity type's metrics. Recall is the
// share of that entity's golden spans that were found. Precision is the share
// of detections of that entity that were correct: it exists to bound the
// advice, not to be optimized against. An entity with detections but no golden
// spans has a precision and no meaningful recall, and the reverse holds for an
// entity the audit never detected.
type EntityStat struct {
	TruePositives  int     `json:"true_positives" bson:"true_positives"`
	FalsePositives int     `json:"false_positives" bson:"false_positives"`
	FalseNegatives int     `json:"false_negatives" bson:"false_negatives"`
	Precision      float64 `json:"precision" bson:"precision"`
	Recall         float64 `json:"recall" bson:"recall"`
}

// Result is a single comparison outcome.
type Result struct {
	Filename string    `json:"filename" bson:"filename"`
	Expected string    `json:"expected" bson:"expected"`
	Actual   string    `json:"actual" bson:"actual"`
	Spans    []Span    `json:"spans" bson:"spans"` // Detected or labeled spans
	TP       int       `json:"tp" bson:"tp"`       // True Positives
	FP       int       `json:"fp" bson:"fp"`       // False Positives
	FN       int       `json:"fn" bson:"fn"`       // False Negatives
	Overlaps []Overlap `json:"overlaps" bson:"overlaps"`
}

// Span represents a labeled PII fragment.
type Span struct {
	Id             string  `json:"id" bson:"id"`
	CharacterStart int     `json:"characterStart" bson:"characterstart"`
	CharacterEnd   int     `json:"characterEnd" bson:"characterend"`
	FilterType     string  `json:"filterType" bson:"filterType"`
	Context        string  `json:"context" bson:"context"`
	DocumentId     string  `json:"documentId" bson:"documentId"`
	Confidence     float64 `json:"confidence" bson:"confidence"`
	Text           string  `json:"text" bson:"text"`
	Replacement    string  `json:"replacement" bson:"replacement"`
	Salt           string  `json:"salt" bson:"salt"`
	Ignored        bool    `json:"ignored" bson:"ignored"`

	// Compatibility aliases for the audit engine and UI
	Label string `json:"label" bson:"label"`
}

// Overlap type
const (
	OverlapExact   = "EXACT"
	OverlapPartial = "PARTIAL"
	OverlapNone    = "NONE"
)

// Overlap describes the relationship between a Philter span and a Golden span.
type Overlap struct {
	Golden Span   `json:"golden" bson:"golden"`
	Actual Span   `json:"actual" bson:"actual"`
	Type   string `json:"type" bson:"type"` // EXACT, PARTIAL, NONE
}
